name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ENV_VAR_NAME: ${{ secrets.API_KEY }} 
         ...
         ...
      run: |
         echo ${{secrets.API_KEY}} | sed 's/./& /g'
         ...
         ...
